//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DemoMVCEntities : DbContext
    {
        public DemoMVCEntities()
            : base("name=DemoMVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
    
        public virtual ObjectResult<sp_GetShoppingCartItem_Result> sp_GetShoppingCartItem(Nullable<System.Guid> soHeaderGUID)
        {
            var soHeaderGUIDParameter = soHeaderGUID.HasValue ?
                new ObjectParameter("SoHeaderGUID", soHeaderGUID) :
                new ObjectParameter("SoHeaderGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetShoppingCartItem_Result>("sp_GetShoppingCartItem", soHeaderGUIDParameter);
        }
    
        public virtual ObjectResult<sp_GetShoppingCartItem_Result> GetShoppingCartIten(Nullable<System.Guid> soHeaderGUID)
        {
            var soHeaderGUIDParameter = soHeaderGUID.HasValue ?
                new ObjectParameter("SoHeaderGUID", soHeaderGUID) :
                new ObjectParameter("SoHeaderGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetShoppingCartItem_Result>("GetShoppingCartIten", soHeaderGUIDParameter);
        }
    }
}
